// <auto-generated />
using System;
using Budgeting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budgeting.Migrations
{
    [DbContext(typeof(BudgetingContext))]
    [Migration("20230731204527_BudgetEntryLists")]
    partial class BudgetEntryLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Budgeting.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("FixedEntry")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FromCreditcard")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MoneyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TimeAmount")
                        .HasColumnType("int");

                    b.Property<bool>("ToSharedAccount")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("TransferTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("BudgetEntry");
                });

            modelBuilder.Entity("Budgeting.Models.BudgetEntryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BudgetEntryId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetEntryId");

                    b.HasIndex("BudgetListId");

                    b.ToTable("BudgetEntryLists");
                });

            modelBuilder.Entity("Budgeting.Models.BudgetList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BudgetList");
                });

            modelBuilder.Entity("Budgeting.Models.BudgetEntryList", b =>
                {
                    b.HasOne("Budgeting.Models.BudgetEntry", "BudgetEntry")
                        .WithMany()
                        .HasForeignKey("BudgetEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgeting.Models.BudgetList", "BudgetList")
                        .WithMany()
                        .HasForeignKey("BudgetListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetEntry");

                    b.Navigation("BudgetList");
                });
#pragma warning restore 612, 618
        }
    }
}
